//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/ryan.szemplinski/projects/dotnet/QLShell/src/QL.Parser/AntlrGenerated/QL.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class QLParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		LOCAL=1, REMOTE=2, BOOLEAN=3, NULL=4, NAME_START=5, NAME=6, STRING=7, 
		NUMBER=8, FLOAT=9, FRACTIONAL=10, EXPONENT=11, INT=12, VARIABLE=13, WS=14, 
		COMMENT=15, LINE_TERMINATOR=16, UNICODE_SCALAR_VALUE_HEX=17, LETTERS=18, 
		EXP=19, HEX=20, UNICODE=21, ESC=22, COLON=23, LPAREN=24, RPAREN=25, LBRACE=26, 
		RBRACE=27, LBRACK=28, RBRACK=29, PIPE=30, COMMA=31;
	public const int
		RULE_document = 0, RULE_action_type = 1, RULE_action_block = 2, RULE_context_blocks = 3, 
		RULE_context_block = 4, RULE_local_context_block = 5, RULE_remote_context_block = 6, 
		RULE_selection_set = 7, RULE_selection = 8, RULE_field = 9, RULE_args = 10, 
		RULE_arg = 11, RULE_transformations = 12, RULE_transformation = 13, RULE_list = 14, 
		RULE_object_field = 15, RULE_object = 16, RULE_value = 17;
	public static readonly string[] ruleNames = {
		"document", "action_type", "action_block", "context_blocks", "context_block", 
		"local_context_block", "remote_context_block", "selection_set", "selection", 
		"field", "args", "arg", "transformations", "transformation", "list", "object_field", 
		"object", "value"
	};

	private static readonly string[] _LiteralNames = {
		null, "'local'", "'remote'", null, "'null'", null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, "':'", "'('", "')'", "'{'", "'}'", "'['", "']'", "'|'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, "LOCAL", "REMOTE", "BOOLEAN", "NULL", "NAME_START", "NAME", "STRING", 
		"NUMBER", "FLOAT", "FRACTIONAL", "EXPONENT", "INT", "VARIABLE", "WS", 
		"COMMENT", "LINE_TERMINATOR", "UNICODE_SCALAR_VALUE_HEX", "LETTERS", "EXP", 
		"HEX", "UNICODE", "ESC", "COLON", "LPAREN", "RPAREN", "LBRACE", "RBRACE", 
		"LBRACK", "RBRACK", "PIPE", "COMMA"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "QL.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static QLParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public QLParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public QLParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class DocumentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Action_blockContext action_block() {
			return GetRuleContext<Action_blockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(QLParser.Eof, 0); }
		public DocumentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_document; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQLVisitor<TResult> typedVisitor = visitor as IQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDocument(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DocumentContext document() {
		DocumentContext _localctx = new DocumentContext(Context, State);
		EnterRule(_localctx, 0, RULE_document);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 36;
			action_block();
			State = 37;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Action_typeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME() { return GetToken(QLParser.NAME, 0); }
		public Action_typeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_action_type; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQLVisitor<TResult> typedVisitor = visitor as IQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAction_type(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Action_typeContext action_type() {
		Action_typeContext _localctx = new Action_typeContext(Context, State);
		EnterRule(_localctx, 2, RULE_action_type);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 39;
			Match(NAME);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Action_blockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Action_typeContext action_type() {
			return GetRuleContext<Action_typeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(QLParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Context_blocksContext context_blocks() {
			return GetRuleContext<Context_blocksContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(QLParser.RBRACE, 0); }
		public Action_blockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_action_block; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQLVisitor<TResult> typedVisitor = visitor as IQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAction_block(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Action_blockContext action_block() {
		Action_blockContext _localctx = new Action_blockContext(Context, State);
		EnterRule(_localctx, 4, RULE_action_block);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 41;
			action_type();
			State = 42;
			Match(LBRACE);
			State = 43;
			context_blocks();
			State = 44;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Context_blocksContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Context_blockContext[] context_block() {
			return GetRuleContexts<Context_blockContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Context_blockContext context_block(int i) {
			return GetRuleContext<Context_blockContext>(i);
		}
		public Context_blocksContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_context_blocks; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQLVisitor<TResult> typedVisitor = visitor as IQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitContext_blocks(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Context_blocksContext context_blocks() {
		Context_blocksContext _localctx = new Context_blocksContext(Context, State);
		EnterRule(_localctx, 6, RULE_context_blocks);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 47;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 46;
				context_block();
				}
				}
				State = 49;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==LOCAL || _la==REMOTE );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Context_blockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Remote_context_blockContext remote_context_block() {
			return GetRuleContext<Remote_context_blockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Local_context_blockContext local_context_block() {
			return GetRuleContext<Local_context_blockContext>(0);
		}
		public Context_blockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_context_block; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQLVisitor<TResult> typedVisitor = visitor as IQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitContext_block(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Context_blockContext context_block() {
		Context_blockContext _localctx = new Context_blockContext(Context, State);
		EnterRule(_localctx, 8, RULE_context_block);
		try {
			State = 53;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case REMOTE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 51;
				remote_context_block();
				}
				break;
			case LOCAL:
				EnterOuterAlt(_localctx, 2);
				{
				State = 52;
				local_context_block();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Local_context_blockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LOCAL() { return GetToken(QLParser.LOCAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Selection_setContext selection_set() {
			return GetRuleContext<Selection_setContext>(0);
		}
		public Local_context_blockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_local_context_block; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQLVisitor<TResult> typedVisitor = visitor as IQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLocal_context_block(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Local_context_blockContext local_context_block() {
		Local_context_blockContext _localctx = new Local_context_blockContext(Context, State);
		EnterRule(_localctx, 10, RULE_local_context_block);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 55;
			Match(LOCAL);
			State = 56;
			selection_set();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Remote_context_blockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REMOTE() { return GetToken(QLParser.REMOTE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgsContext args() {
			return GetRuleContext<ArgsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Selection_setContext selection_set() {
			return GetRuleContext<Selection_setContext>(0);
		}
		public Remote_context_blockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_remote_context_block; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQLVisitor<TResult> typedVisitor = visitor as IQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRemote_context_block(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Remote_context_blockContext remote_context_block() {
		Remote_context_blockContext _localctx = new Remote_context_blockContext(Context, State);
		EnterRule(_localctx, 12, RULE_remote_context_block);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 58;
			Match(REMOTE);
			State = 59;
			args();
			State = 60;
			selection_set();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Selection_setContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(QLParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(QLParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SelectionContext[] selection() {
			return GetRuleContexts<SelectionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public SelectionContext selection(int i) {
			return GetRuleContext<SelectionContext>(i);
		}
		public Selection_setContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_selection_set; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQLVisitor<TResult> typedVisitor = visitor as IQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSelection_set(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Selection_setContext selection_set() {
		Selection_setContext _localctx = new Selection_setContext(Context, State);
		EnterRule(_localctx, 14, RULE_selection_set);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 62;
			Match(LBRACE);
			State = 64;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 63;
				selection();
				}
				}
				State = 66;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==NAME );
			State = 68;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SelectionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FieldContext field() {
			return GetRuleContext<FieldContext>(0);
		}
		public SelectionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_selection; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQLVisitor<TResult> typedVisitor = visitor as IQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSelection(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SelectionContext selection() {
		SelectionContext _localctx = new SelectionContext(Context, State);
		EnterRule(_localctx, 16, RULE_selection);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 70;
			field();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME() { return GetToken(QLParser.NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgsContext args() {
			return GetRuleContext<ArgsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Selection_setContext selection_set() {
			return GetRuleContext<Selection_setContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TransformationsContext transformations() {
			return GetRuleContext<TransformationsContext>(0);
		}
		public FieldContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_field; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQLVisitor<TResult> typedVisitor = visitor as IQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitField(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FieldContext field() {
		FieldContext _localctx = new FieldContext(Context, State);
		EnterRule(_localctx, 18, RULE_field);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 72;
			Match(NAME);
			State = 74;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LPAREN) {
				{
				State = 73;
				args();
				}
			}

			State = 77;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LBRACE) {
				{
				State = 76;
				selection_set();
				}
			}

			State = 80;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==PIPE) {
				{
				State = 79;
				transformations();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(QLParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgContext[] arg() {
			return GetRuleContexts<ArgContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgContext arg(int i) {
			return GetRuleContext<ArgContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(QLParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(QLParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(QLParser.COMMA, i);
		}
		public ArgsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_args; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQLVisitor<TResult> typedVisitor = visitor as IQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgs(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgsContext args() {
		ArgsContext _localctx = new ArgsContext(Context, State);
		EnterRule(_localctx, 20, RULE_args);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 82;
			Match(LPAREN);
			State = 83;
			arg();
			State = 88;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 84;
				Match(COMMA);
				State = 85;
				arg();
				}
				}
				State = 90;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 91;
			Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME() { return GetToken(QLParser.NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(QLParser.COLON, 0); }
		public ArgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQLVisitor<TResult> typedVisitor = visitor as IQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgContext arg() {
		ArgContext _localctx = new ArgContext(Context, State);
		EnterRule(_localctx, 22, RULE_arg);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 95;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==NAME) {
				{
				State = 93;
				Match(NAME);
				State = 94;
				Match(COLON);
				}
			}

			State = 97;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TransformationsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TransformationContext[] transformation() {
			return GetRuleContexts<TransformationContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TransformationContext transformation(int i) {
			return GetRuleContext<TransformationContext>(i);
		}
		public TransformationsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_transformations; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQLVisitor<TResult> typedVisitor = visitor as IQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTransformations(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TransformationsContext transformations() {
		TransformationsContext _localctx = new TransformationsContext(Context, State);
		EnterRule(_localctx, 24, RULE_transformations);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 99;
				transformation();
				}
				}
				State = 102;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==PIPE );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TransformationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PIPE() { return GetToken(QLParser.PIPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME() { return GetToken(QLParser.NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgsContext args() {
			return GetRuleContext<ArgsContext>(0);
		}
		public TransformationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_transformation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQLVisitor<TResult> typedVisitor = visitor as IQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTransformation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TransformationContext transformation() {
		TransformationContext _localctx = new TransformationContext(Context, State);
		EnterRule(_localctx, 26, RULE_transformation);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 104;
			Match(PIPE);
			State = 105;
			Match(NAME);
			State = 107;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LPAREN) {
				{
				State = 106;
				args();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACK() { return GetToken(QLParser.LBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACK() { return GetToken(QLParser.RBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext[] value() {
			return GetRuleContexts<ValueContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value(int i) {
			return GetRuleContext<ValueContext>(i);
		}
		public ListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_list; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQLVisitor<TResult> typedVisitor = visitor as IQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ListContext list() {
		ListContext _localctx = new ListContext(Context, State);
		EnterRule(_localctx, 28, RULE_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 109;
			Match(LBRACK);
			State = 113;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 335552920L) != 0)) {
				{
				{
				State = 110;
				value();
				}
				}
				State = 115;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 116;
			Match(RBRACK);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Object_fieldContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME() { return GetToken(QLParser.NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(QLParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public Object_fieldContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_object_field; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQLVisitor<TResult> typedVisitor = visitor as IQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitObject_field(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Object_fieldContext object_field() {
		Object_fieldContext _localctx = new Object_fieldContext(Context, State);
		EnterRule(_localctx, 30, RULE_object_field);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 118;
			Match(NAME);
			State = 119;
			Match(COLON);
			State = 120;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ObjectContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(QLParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(QLParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Object_fieldContext[] object_field() {
			return GetRuleContexts<Object_fieldContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Object_fieldContext object_field(int i) {
			return GetRuleContext<Object_fieldContext>(i);
		}
		public ObjectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_object; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQLVisitor<TResult> typedVisitor = visitor as IQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitObject(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ObjectContext @object() {
		ObjectContext _localctx = new ObjectContext(Context, State);
		EnterRule(_localctx, 32, RULE_object);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 122;
			Match(LBRACE);
			State = 126;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==NAME) {
				{
				{
				State = 123;
				object_field();
				}
				}
				State = 128;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 129;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE() { return GetToken(QLParser.VARIABLE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOLEAN() { return GetToken(QLParser.BOOLEAN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(QLParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(QLParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NULL() { return GetToken(QLParser.NULL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ListContext list() {
			return GetRuleContext<ListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ObjectContext @object() {
			return GetRuleContext<ObjectContext>(0);
		}
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQLVisitor<TResult> typedVisitor = visitor as IQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 34, RULE_value);
		try {
			State = 138;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case VARIABLE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 131;
				Match(VARIABLE);
				}
				break;
			case BOOLEAN:
				EnterOuterAlt(_localctx, 2);
				{
				State = 132;
				Match(BOOLEAN);
				}
				break;
			case NUMBER:
				EnterOuterAlt(_localctx, 3);
				{
				State = 133;
				Match(NUMBER);
				}
				break;
			case STRING:
				EnterOuterAlt(_localctx, 4);
				{
				State = 134;
				Match(STRING);
				}
				break;
			case NULL:
				EnterOuterAlt(_localctx, 5);
				{
				State = 135;
				Match(NULL);
				}
				break;
			case LBRACK:
				EnterOuterAlt(_localctx, 6);
				{
				State = 136;
				list();
				}
				break;
			case LBRACE:
				EnterOuterAlt(_localctx, 7);
				{
				State = 137;
				@object();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,31,141,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,1,0,1,0,1,0,1,1,1,1,1,2,1,2,1,2,1,2,1,2,
		1,3,4,3,48,8,3,11,3,12,3,49,1,4,1,4,3,4,54,8,4,1,5,1,5,1,5,1,6,1,6,1,6,
		1,6,1,7,1,7,4,7,65,8,7,11,7,12,7,66,1,7,1,7,1,8,1,8,1,9,1,9,3,9,75,8,9,
		1,9,3,9,78,8,9,1,9,3,9,81,8,9,1,10,1,10,1,10,1,10,5,10,87,8,10,10,10,12,
		10,90,9,10,1,10,1,10,1,11,1,11,3,11,96,8,11,1,11,1,11,1,12,4,12,101,8,
		12,11,12,12,12,102,1,13,1,13,1,13,3,13,108,8,13,1,14,1,14,5,14,112,8,14,
		10,14,12,14,115,9,14,1,14,1,14,1,15,1,15,1,15,1,15,1,16,1,16,5,16,125,
		8,16,10,16,12,16,128,9,16,1,16,1,16,1,17,1,17,1,17,1,17,1,17,1,17,1,17,
		3,17,139,8,17,1,17,0,0,18,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,
		34,0,0,140,0,36,1,0,0,0,2,39,1,0,0,0,4,41,1,0,0,0,6,47,1,0,0,0,8,53,1,
		0,0,0,10,55,1,0,0,0,12,58,1,0,0,0,14,62,1,0,0,0,16,70,1,0,0,0,18,72,1,
		0,0,0,20,82,1,0,0,0,22,95,1,0,0,0,24,100,1,0,0,0,26,104,1,0,0,0,28,109,
		1,0,0,0,30,118,1,0,0,0,32,122,1,0,0,0,34,138,1,0,0,0,36,37,3,4,2,0,37,
		38,5,0,0,1,38,1,1,0,0,0,39,40,5,6,0,0,40,3,1,0,0,0,41,42,3,2,1,0,42,43,
		5,26,0,0,43,44,3,6,3,0,44,45,5,27,0,0,45,5,1,0,0,0,46,48,3,8,4,0,47,46,
		1,0,0,0,48,49,1,0,0,0,49,47,1,0,0,0,49,50,1,0,0,0,50,7,1,0,0,0,51,54,3,
		12,6,0,52,54,3,10,5,0,53,51,1,0,0,0,53,52,1,0,0,0,54,9,1,0,0,0,55,56,5,
		1,0,0,56,57,3,14,7,0,57,11,1,0,0,0,58,59,5,2,0,0,59,60,3,20,10,0,60,61,
		3,14,7,0,61,13,1,0,0,0,62,64,5,26,0,0,63,65,3,16,8,0,64,63,1,0,0,0,65,
		66,1,0,0,0,66,64,1,0,0,0,66,67,1,0,0,0,67,68,1,0,0,0,68,69,5,27,0,0,69,
		15,1,0,0,0,70,71,3,18,9,0,71,17,1,0,0,0,72,74,5,6,0,0,73,75,3,20,10,0,
		74,73,1,0,0,0,74,75,1,0,0,0,75,77,1,0,0,0,76,78,3,14,7,0,77,76,1,0,0,0,
		77,78,1,0,0,0,78,80,1,0,0,0,79,81,3,24,12,0,80,79,1,0,0,0,80,81,1,0,0,
		0,81,19,1,0,0,0,82,83,5,24,0,0,83,88,3,22,11,0,84,85,5,31,0,0,85,87,3,
		22,11,0,86,84,1,0,0,0,87,90,1,0,0,0,88,86,1,0,0,0,88,89,1,0,0,0,89,91,
		1,0,0,0,90,88,1,0,0,0,91,92,5,25,0,0,92,21,1,0,0,0,93,94,5,6,0,0,94,96,
		5,23,0,0,95,93,1,0,0,0,95,96,1,0,0,0,96,97,1,0,0,0,97,98,3,34,17,0,98,
		23,1,0,0,0,99,101,3,26,13,0,100,99,1,0,0,0,101,102,1,0,0,0,102,100,1,0,
		0,0,102,103,1,0,0,0,103,25,1,0,0,0,104,105,5,30,0,0,105,107,5,6,0,0,106,
		108,3,20,10,0,107,106,1,0,0,0,107,108,1,0,0,0,108,27,1,0,0,0,109,113,5,
		28,0,0,110,112,3,34,17,0,111,110,1,0,0,0,112,115,1,0,0,0,113,111,1,0,0,
		0,113,114,1,0,0,0,114,116,1,0,0,0,115,113,1,0,0,0,116,117,5,29,0,0,117,
		29,1,0,0,0,118,119,5,6,0,0,119,120,5,23,0,0,120,121,3,34,17,0,121,31,1,
		0,0,0,122,126,5,26,0,0,123,125,3,30,15,0,124,123,1,0,0,0,125,128,1,0,0,
		0,126,124,1,0,0,0,126,127,1,0,0,0,127,129,1,0,0,0,128,126,1,0,0,0,129,
		130,5,27,0,0,130,33,1,0,0,0,131,139,5,13,0,0,132,139,5,3,0,0,133,139,5,
		8,0,0,134,139,5,7,0,0,135,139,5,4,0,0,136,139,3,28,14,0,137,139,3,32,16,
		0,138,131,1,0,0,0,138,132,1,0,0,0,138,133,1,0,0,0,138,134,1,0,0,0,138,
		135,1,0,0,0,138,136,1,0,0,0,138,137,1,0,0,0,139,35,1,0,0,0,13,49,53,66,
		74,77,80,88,95,102,107,113,126,138
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
