//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/rszemplinski/projects/dotnet/QLShell/QL.Parser/QL.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="QLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IQLVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDocument([NotNull] QLParser.DocumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLParser.action_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAction_type([NotNull] QLParser.Action_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLParser.action_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAction_block([NotNull] QLParser.Action_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLParser.context_blocks"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContext_blocks([NotNull] QLParser.Context_blocksContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLParser.context_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContext_block([NotNull] QLParser.Context_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLParser.local_context_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_context_block([NotNull] QLParser.Local_context_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLParser.remote_context_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRemote_context_block([NotNull] QLParser.Remote_context_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLParser.selection_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelection_set([NotNull] QLParser.Selection_setContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLParser.selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelection([NotNull] QLParser.SelectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField([NotNull] QLParser.FieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgs([NotNull] QLParser.ArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArg([NotNull] QLParser.ArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLParser.transformations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransformations([NotNull] QLParser.TransformationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLParser.transformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransformation([NotNull] QLParser.TransformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] QLParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList([NotNull] QLParser.ListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLParser.object_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject_field([NotNull] QLParser.Object_fieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject([NotNull] QLParser.ObjectContext context);
}
